// A broad, categorized emoji set for the picker. Unicode defines ~3,900 emojis;
// this is a practical, commonly-used subset (a few hundred) across every
// category, which is what mainstream chat apps ship. Each entry is
// [emoji, keywords] — keywords power search.
export type EmojiCategory = { key: string; label: string; icon: string; emojis: [string, string][] };

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    key: 'smileys',
    label: 'Smileys & Emotion',
    icon: '😀',
    emojis: [
      ['😀', 'grinning smile happy'], ['😃', 'smiley happy'], ['😄', 'smile happy joy'], ['😁', 'grin beaming'],
      ['😆', 'laughing satisfied'], ['😅', 'sweat smile nervous'], ['🤣', 'rofl rolling laughing'], ['😂', 'joy lol laugh tears'],
      ['🙂', 'slight smile'], ['🙃', 'upside down silly'], ['🫠', 'melting'], ['😉', 'wink flirt'],
      ['😊', 'blush happy'], ['😇', 'innocent angel halo'], ['🥰', 'smiling hearts love'], ['😍', 'heart eyes love'],
      ['🤩', 'star struck excited'], ['😘', 'blowing kiss love'], ['😗', 'kissing'], ['😚', 'kissing closed eyes'],
      ['😙', 'kissing smiling'], ['🥲', 'smiling tear'], ['😋', 'yum tasty'], ['😛', 'tongue'],
      ['😜', 'winking tongue'], ['🤪', 'zany crazy'], ['😝', 'squinting tongue'], ['🤑', 'money mouth rich'],
      ['🤗', 'hugging hug'], ['🤭', 'hand over mouth oops'], ['🫢', 'shush surprise'], ['🤫', 'shushing quiet'],
      ['🤔', 'thinking hmm'], ['🫡', 'saluting'], ['🤐', 'zipper mouth'], ['🤨', 'raised eyebrow'],
      ['😐', 'neutral'], ['😑', 'expressionless'], ['😶', 'no mouth speechless'], ['🫥', 'dotted line invisible'],
      ['😏', 'smirk'], ['😒', 'unamused meh'], ['🙄', 'rolling eyes'], ['😬', 'grimacing awkward'],
      ['🤥', 'lying liar'], ['😌', 'relieved calm'], ['😔', 'pensive sad'], ['😪', 'sleepy'],
      ['🤤', 'drooling'], ['😴', 'sleeping tired zzz'], ['😷', 'mask sick'], ['🤒', 'thermometer sick'],
      ['🤕', 'bandage hurt'], ['🤢', 'nauseated sick'], ['🤮', 'vomiting'], ['🤧', 'sneezing'],
      ['🥵', 'hot heat'], ['🥶', 'cold freezing'], ['🥴', 'woozy dizzy'], ['😵', 'dizzy'],
      ['🤯', 'mind blown exploding'], ['🤠', 'cowboy'], ['🥳', 'partying celebrate'], ['🥸', 'disguise'],
      ['😎', 'sunglasses cool'], ['🤓', 'nerd geek'], ['🧐', 'monocle'], ['😕', 'confused'],
      ['🫤', 'diagonal mouth'], ['😟', 'worried'], ['🙁', 'frowning'], ['😮', 'open mouth wow'],
      ['😯', 'hushed'], ['😲', 'astonished shocked'], ['😳', 'flushed embarrassed'], ['🥺', 'pleading puppy eyes'],
      ['🥹', 'holding back tears'], ['😦', 'frowning open'], ['😧', 'anguished'], ['😨', 'fearful scared'],
      ['😰', 'anxious sweat'], ['😥', 'sad relieved'], ['😢', 'cry sad tear'], ['😭', 'sobbing crying'],
      ['😱', 'scream fear'], ['😖', 'confounded'], ['😣', 'persevering'], ['😞', 'disappointed'],
      ['😓', 'downcast sweat'], ['😩', 'weary'], ['😫', 'tired'], ['🥱', 'yawning bored'],
      ['😤', 'triumph steam'], ['😡', 'angry mad rage'], ['😠', 'angry'], ['🤬', 'cursing swearing'],
      ['😈', 'devil smiling'], ['👿', 'imp angry devil'], ['💀', 'skull dead'], ['💩', 'poop'],
      ['🤡', 'clown'], ['👻', 'ghost'], ['👽', 'alien'], ['🤖', 'robot'],
    ],
  },
  {
    key: 'people',
    label: 'People & Body',
    icon: '👍',
    emojis: [
      ['👋', 'wave hello hi bye'], ['🤚', 'raised back hand'], ['🖐️', 'hand fingers'], ['✋', 'raised hand stop'],
      ['🖖', 'vulcan spock'], ['👌', 'ok perfect'], ['🤌', 'pinched fingers'], ['🤏', 'pinch small'],
      ['✌️', 'victory peace'], ['🤞', 'crossed fingers luck'], ['🫰', 'fingers crossed heart'], ['🤟', 'love you gesture'],
      ['🤘', 'rock horns'], ['🤙', 'call me shaka'], ['👈', 'point left'], ['👉', 'point right'],
      ['👆', 'point up'], ['🖕', 'middle finger'], ['👇', 'point down'], ['☝️', 'index up'],
      ['👍', 'thumbs up ok yes like'], ['👎', 'thumbs down no dislike'], ['✊', 'fist raised'], ['👊', 'fist bump punch'],
      ['🤛', 'left fist'], ['🤜', 'right fist'], ['👏', 'clap applause congrats'], ['🙌', 'raised hands yay praise'],
      ['🫶', 'heart hands love'], ['👐', 'open hands'], ['🤲', 'palms up'], ['🤝', 'handshake deal'],
      ['🙏', 'pray please thanks'], ['✍️', 'writing'], ['💅', 'nails'], ['🤳', 'selfie'],
      ['💪', 'muscle strong flex'], ['🦾', 'mechanical arm'], ['🦵', 'leg'], ['🦶', 'foot'],
      ['👂', 'ear'], ['👃', 'nose'], ['🧠', 'brain'], ['🫀', 'heart organ'],
      ['🦷', 'tooth'], ['👀', 'eyes look'], ['👁️', 'eye'], ['👅', 'tongue'],
      ['👄', 'mouth lips'], ['🫦', 'biting lip'], ['👶', 'baby'], ['🧒', 'child'],
      ['👦', 'boy'], ['👧', 'girl'], ['🧑', 'person'], ['👨', 'man'],
      ['👩', 'woman'], ['🧔', 'beard'], ['👴', 'old man'], ['👵', 'old woman'],
      ['🙋', 'raising hand'], ['🤦', 'facepalm'], ['🤷', 'shrug idk'], ['🧍', 'standing'],
      ['🚶', 'walking'], ['🏃', 'running'], ['💃', 'dancing woman'], ['🕺', 'dancing man'],
      ['👪', 'family'], ['🧑‍🤝‍🧑', 'people holding hands'], ['👫', 'couple'], ['💏', 'kiss couple'],
      ['💑', 'couple heart'], ['🫂', 'hug people'],
    ],
  },
  {
    key: 'nature',
    label: 'Animals & Nature',
    icon: '🐶',
    emojis: [
      ['🐶', 'dog puppy'], ['🐱', 'cat'], ['🐭', 'mouse'], ['🐹', 'hamster'], ['🐰', 'rabbit bunny'],
      ['🦊', 'fox'], ['🐻', 'bear'], ['🐼', 'panda'], ['🐨', 'koala'], ['🐯', 'tiger'],
      ['🦁', 'lion'], ['🐮', 'cow'], ['🐷', 'pig'], ['🐸', 'frog'], ['🐵', 'monkey'],
      ['🙈', 'see no evil monkey'], ['🙉', 'hear no evil monkey'], ['🙊', 'speak no evil monkey'], ['🐔', 'chicken'], ['🐧', 'penguin'],
      ['🐦', 'bird'], ['🐤', 'chick'], ['🦆', 'duck'], ['🦅', 'eagle'], ['🦉', 'owl'],
      ['🦇', 'bat'], ['🐺', 'wolf'], ['🐗', 'boar'], ['🐴', 'horse'], ['🦄', 'unicorn'],
      ['🐝', 'bee'], ['🐛', 'bug caterpillar'], ['🦋', 'butterfly'], ['🐌', 'snail'], ['🐞', 'ladybug'],
      ['🐜', 'ant'], ['🦗', 'cricket'], ['🕷️', 'spider'], ['🦂', 'scorpion'], ['🐢', 'turtle'],
      ['🐍', 'snake'], ['🦎', 'lizard'], ['🐙', 'octopus'], ['🦑', 'squid'], ['🦐', 'shrimp'],
      ['🦀', 'crab'], ['🐡', 'blowfish'], ['🐠', 'tropical fish'], ['🐟', 'fish'], ['🐬', 'dolphin'],
      ['🐳', 'whale'], ['🦈', 'shark'], ['🐊', 'crocodile'], ['🐘', 'elephant'], ['🦒', 'giraffe'],
      ['🐪', 'camel'], ['🦓', 'zebra'], ['🐎', 'racehorse'], ['🐖', 'pig'], ['🐏', 'ram'],
      ['🐑', 'sheep'], ['🐐', 'goat'], ['🌵', 'cactus'], ['🌲', 'evergreen tree'], ['🌳', 'tree'],
      ['🌴', 'palm tree'], ['🌱', 'seedling'], ['🌿', 'herb'], ['☘️', 'shamrock'], ['🍀', 'four leaf clover luck'],
      ['🎍', 'bamboo'], ['🍂', 'fallen leaves'], ['🍁', 'maple leaf'], ['🍄', 'mushroom'], ['🌾', 'wheat'],
      ['💐', 'bouquet flowers'], ['🌷', 'tulip'], ['🌹', 'rose'], ['🥀', 'wilted flower'], ['🌺', 'hibiscus'],
      ['🌸', 'cherry blossom'], ['🌼', 'blossom'], ['🌻', 'sunflower'], ['🌞', 'sun face'], ['🌝', 'full moon face'],
      ['🌜', 'moon face'], ['🌙', 'crescent moon'], ['⭐', 'star'], ['🌟', 'glowing star'], ['✨', 'sparkles shine'],
      ['⚡', 'lightning bolt'], ['🔥', 'fire lit hot'], ['🌈', 'rainbow'], ['☀️', 'sun sunny'], ['⛅', 'partly cloudy'],
      ['☁️', 'cloud'], ['🌧️', 'rain'], ['⛈️', 'storm thunder'], ['❄️', 'snowflake cold'], ['⛄', 'snowman'],
      ['💧', 'droplet water'], ['🌊', 'wave ocean'],
    ],
  },
  {
    key: 'food',
    label: 'Food & Drink',
    icon: '🍔',
    emojis: [
      ['🍏', 'green apple'], ['🍎', 'apple'], ['🍐', 'pear'], ['🍊', 'orange tangerine'], ['🍋', 'lemon'],
      ['🍌', 'banana'], ['🍉', 'watermelon'], ['🍇', 'grapes'], ['🍓', 'strawberry'], ['🫐', 'blueberries'],
      ['🍈', 'melon'], ['🍒', 'cherries'], ['🍑', 'peach'], ['🥭', 'mango'], ['🍍', 'pineapple'],
      ['🥥', 'coconut'], ['🥝', 'kiwi'], ['🍅', 'tomato'], ['🍆', 'eggplant'], ['🥑', 'avocado'],
      ['🥦', 'broccoli'], ['🥬', 'leafy green'], ['🥒', 'cucumber'], ['🌶️', 'hot pepper spicy'], ['🌽', 'corn'],
      ['🥕', 'carrot'], ['🧄', 'garlic'], ['🧅', 'onion'], ['🥔', 'potato'], ['🍠', 'sweet potato'],
      ['🥐', 'croissant'], ['🥯', 'bagel'], ['🍞', 'bread'], ['🥖', 'baguette'], ['🧀', 'cheese'],
      ['🥚', 'egg'], ['🍳', 'fried egg cooking'], ['🥞', 'pancakes'], ['🧇', 'waffle'], ['🥓', 'bacon'],
      ['🍔', 'burger hamburger'], ['🍟', 'fries'], ['🍕', 'pizza'], ['🌭', 'hot dog'], ['🥪', 'sandwich'],
      ['🌮', 'taco'], ['🌯', 'burrito'], ['🥗', 'salad'], ['🍝', 'spaghetti pasta'], ['🍜', 'ramen noodles'],
      ['🍲', 'stew'], ['🍛', 'curry'], ['🍣', 'sushi'], ['🍱', 'bento'], ['🍚', 'rice'],
      ['🍙', 'rice ball'], ['🍘', 'rice cracker'], ['🍥', 'fish cake'], ['🥟', 'dumpling'], ['🍤', 'shrimp fried'],
      ['🍦', 'ice cream soft'], ['🍧', 'shaved ice'], ['🍨', 'ice cream'], ['🍩', 'donut'], ['🍪', 'cookie'],
      ['🎂', 'birthday cake'], ['🍰', 'cake slice'], ['🧁', 'cupcake'], ['🥧', 'pie'], ['🍫', 'chocolate'],
      ['🍬', 'candy'], ['🍭', 'lollipop'], ['🍯', 'honey'], ['🍼', 'baby bottle'], ['🥛', 'milk'],
      ['☕', 'coffee'], ['🍵', 'tea'], ['🧃', 'juice box'], ['🥤', 'soda drink'], ['🧋', 'bubble tea boba'],
      ['🍺', 'beer'], ['🍻', 'beers cheers'], ['🥂', 'champagne cheers'], ['🍷', 'wine'], ['🥃', 'whiskey'],
      ['🍸', 'cocktail'], ['🍹', 'tropical drink'], ['🍾', 'champagne bottle'],
    ],
  },
  {
    key: 'activities',
    label: 'Activities',
    icon: '⚽',
    emojis: [
      ['⚽', 'soccer football'], ['🏀', 'basketball'], ['🏈', 'american football'], ['⚾', 'baseball'], ['🥎', 'softball'],
      ['🎾', 'tennis'], ['🏐', 'volleyball'], ['🏉', 'rugby'], ['🥏', 'frisbee'], ['🎱', '8 ball pool'],
      ['🏓', 'ping pong'], ['🏸', 'badminton'], ['🥅', 'goal'], ['🏒', 'hockey'], ['🏑', 'field hockey'],
      ['🥍', 'lacrosse'], ['🏏', 'cricket'], ['⛳', 'golf'], ['🏹', 'bow archery'], ['🎣', 'fishing'],
      ['🥊', 'boxing'], ['🥋', 'martial arts'], ['🎽', 'running shirt'], ['⛸️', 'ice skate'], ['🥌', 'curling'],
      ['🛷', 'sled'], ['🎿', 'ski'], ['⛷️', 'skier'], ['🏂', 'snowboard'], ['🏋️', 'weight lifting gym'],
      ['🤼', 'wrestling'], ['🤸', 'cartwheel gymnastics'], ['⛹️', 'basketball player'], ['🤺', 'fencing'], ['🏌️', 'golfer'],
      ['🏇', 'horse racing'], ['🧘', 'yoga meditation'], ['🏄', 'surfing'], ['🏊', 'swimming'], ['🤽', 'water polo'],
      ['🚣', 'rowing'], ['🧗', 'climbing'], ['🚴', 'cycling'], ['🚵', 'mountain biking'], ['🏆', 'trophy win'],
      ['🥇', 'gold medal first'], ['🥈', 'silver medal'], ['🥉', 'bronze medal'], ['🏅', 'medal'], ['🎖️', 'military medal'],
      ['🎯', 'dart target bullseye'], ['🎳', 'bowling'], ['🎮', 'video game controller'], ['🕹️', 'joystick'], ['🎲', 'dice'],
      ['🧩', 'puzzle'], ['🎨', 'art paint'], ['🎭', 'theater masks'], ['🎤', 'microphone sing'], ['🎧', 'headphones'],
      ['🎼', 'music score'], ['🎹', 'piano keyboard'], ['🥁', 'drum'], ['🎸', 'guitar'], ['🎺', 'trumpet'],
      ['🎻', 'violin'], ['🎬', 'clapper film movie'], ['🎪', 'circus tent'],
    ],
  },
  {
    key: 'travel',
    label: 'Travel & Places',
    icon: '🚗',
    emojis: [
      ['🚗', 'car'], ['🚕', 'taxi'], ['🚙', 'suv'], ['🚌', 'bus'], ['🚎', 'trolleybus'],
      ['🏎️', 'race car'], ['🚓', 'police car'], ['🚑', 'ambulance'], ['🚒', 'fire truck'], ['🚐', 'minibus'],
      ['🚚', 'truck'], ['🚛', 'lorry'], ['🚜', 'tractor'], ['🛵', 'scooter'], ['🏍️', 'motorcycle'],
      ['🚲', 'bicycle bike'], ['🛴', 'kick scooter'], ['🚨', 'siren'], ['🚔', 'police'], ['🚍', 'oncoming bus'],
      ['✈️', 'airplane flight'], ['🛫', 'takeoff'], ['🛬', 'landing'], ['🚀', 'rocket launch'], ['🛸', 'ufo'],
      ['🚁', 'helicopter'], ['⛵', 'sailboat'], ['🚤', 'speedboat'], ['🛥️', 'motor boat'], ['🚢', 'ship'],
      ['⚓', 'anchor'], ['🚉', 'station'], ['🚂', 'train'], ['🚆', 'train'], ['🚊', 'tram'],
      ['🚇', 'metro subway'], ['🚝', 'monorail'], ['🚋', 'tram car'], ['🎡', 'ferris wheel'], ['🎢', 'roller coaster'],
      ['🎠', 'carousel'], ['🏗️', 'construction'], ['🏭', 'factory'], ['🏢', 'office building'], ['🏬', 'department store'],
      ['🏣', 'post office'], ['🏤', 'post office'], ['🏥', 'hospital'], ['🏦', 'bank'], ['🏨', 'hotel'],
      ['🏪', 'convenience store'], ['🏫', 'school'], ['🏩', 'love hotel'], ['💒', 'wedding'], ['🏛️', 'classical building'],
      ['⛪', 'church'], ['🕌', 'mosque'], ['🕍', 'synagogue'], ['🛕', 'temple'], ['🏰', 'castle'],
      ['🏯', 'japanese castle'], ['🗼', 'tower'], ['🗽', 'statue of liberty'], ['🏠', 'house home'], ['🏡', 'house garden'],
      ['🏘️', 'houses'], ['🏚️', 'derelict house'], ['⛺', 'tent camping'], ['🏕️', 'camping'], ['🏖️', 'beach'],
      ['🏜️', 'desert'], ['🏝️', 'island'], ['🏞️', 'national park'], ['🌋', 'volcano'], ['🗻', 'mount fuji'],
      ['⛰️', 'mountain'], ['🏔️', 'snow mountain'], ['🌅', 'sunrise'], ['🌄', 'sunrise mountains'], ['🌇', 'sunset city'],
      ['🌆', 'dusk city'], ['🌃', 'night stars'], ['🌌', 'milky way galaxy'], ['🌉', 'bridge night'], ['🎑', 'moon viewing'],
    ],
  },
  {
    key: 'objects',
    label: 'Objects',
    icon: '💡',
    emojis: [
      ['⌚', 'watch'], ['📱', 'phone mobile'], ['💻', 'laptop computer'], ['⌨️', 'keyboard'], ['🖥️', 'desktop'],
      ['🖨️', 'printer'], ['🖱️', 'mouse'], ['💽', 'minidisc'], ['💾', 'floppy save'], ['💿', 'cd'],
      ['📀', 'dvd'], ['📷', 'camera'], ['📸', 'camera flash'], ['📹', 'video camera'], ['🎥', 'movie camera'],
      ['📞', 'phone call'], ['☎️', 'telephone'], ['📟', 'pager'], ['📠', 'fax'], ['📺', 'tv television'],
      ['📻', 'radio'], ['🎙️', 'studio mic'], ['⏱️', 'stopwatch'], ['⏰', 'alarm clock'], ['🕰️', 'mantel clock'],
      ['⌛', 'hourglass'], ['⏳', 'hourglass flowing'], ['🔋', 'battery'], ['🔌', 'plug'], ['💡', 'light bulb idea'],
      ['🔦', 'flashlight'], ['🕯️', 'candle'], ['🧯', 'fire extinguisher'], ['🛢️', 'oil drum'], ['💸', 'money flying'],
      ['💵', 'dollar cash'], ['💴', 'yen'], ['💶', 'euro'], ['💷', 'pound'], ['💰', 'money bag'],
      ['💳', 'credit card'], ['🧾', 'receipt'], ['💎', 'gem diamond'], ['⚖️', 'balance scale'], ['🔧', 'wrench'],
      ['🔨', 'hammer'], ['⚒️', 'hammer pick'], ['🛠️', 'tools'], ['⛏️', 'pick'], ['🔩', 'nut bolt'],
      ['⚙️', 'gear settings'], ['🧰', 'toolbox'], ['🧲', 'magnet'], ['🔫', 'water gun'], ['💣', 'bomb'],
      ['🧨', 'firecracker'], ['🔪', 'knife'], ['🗡️', 'dagger'], ['⚔️', 'swords'], ['🛡️', 'shield'],
      ['🚬', 'cigarette'], ['⚰️', 'coffin'], ['🪦', 'headstone'], ['🏺', 'amphora'], ['🔮', 'crystal ball'],
      ['📿', 'prayer beads'], ['🧿', 'nazar amulet'], ['💈', 'barber'], ['⚗️', 'alembic'], ['🔭', 'telescope'],
      ['🔬', 'microscope'], ['🕳️', 'hole'], ['💊', 'pill medicine'], ['💉', 'syringe'], ['🩸', 'blood drop'],
      ['🩹', 'bandage'], ['🩺', 'stethoscope'], ['🚪', 'door'], ['🛗', 'elevator'], ['🪑', 'chair'],
      ['🚽', 'toilet'], ['🚿', 'shower'], ['🛁', 'bathtub'], ['🧴', 'lotion'], ['🧷', 'safety pin'],
      ['🧹', 'broom'], ['🧺', 'basket'], ['🧻', 'toilet paper'], ['🧼', 'soap'], ['🪥', 'toothbrush'],
      ['🔑', 'key'], ['🗝️', 'old key'], ['🔒', 'lock'], ['🔓', 'unlock'], ['🔐', 'lock key'],
      ['📎', 'paperclip'], ['📌', 'pushpin'], ['📍', 'round pin location'], ['✂️', 'scissors'], ['📏', 'ruler'],
      ['📐', 'triangle ruler'], ['🖊️', 'pen'], ['🖋️', 'fountain pen'], ['✏️', 'pencil'], ['🖍️', 'crayon'],
      ['📝', 'memo note'], ['📖', 'open book'], ['📚', 'books'], ['📔', 'notebook'], ['📓', 'notebook'],
      ['📒', 'ledger'], ['📄', 'page'], ['📃', 'page curl'], ['📑', 'bookmark tabs'], ['📊', 'bar chart'],
      ['📈', 'chart up'], ['📉', 'chart down'], ['🗂️', 'card dividers'], ['📁', 'folder'], ['📂', 'open folder'],
      ['🗒️', 'spiral notepad'], ['📅', 'calendar'], ['📆', 'calendar'], ['🗓️', 'spiral calendar'], ['📇', 'card index'],
      ['🗃️', 'card box'], ['🗄️', 'file cabinet'], ['📋', 'clipboard'], ['📁', 'folder'], ['✉️', 'envelope mail'],
      ['📧', 'email'], ['📨', 'incoming envelope'], ['📩', 'envelope arrow'], ['📤', 'outbox'], ['📥', 'inbox'],
      ['📦', 'package box'], ['🏷️', 'label tag'], ['🎁', 'gift present'], ['🎀', 'ribbon'], ['🎈', 'balloon'],
      ['🎉', 'party popper celebrate'], ['🎊', 'confetti ball'], ['🪅', 'pinata'], ['🎏', 'carp streamer'], ['🎐', 'wind chime'],
    ],
  },
  {
    key: 'symbols',
    label: 'Symbols',
    icon: '❤️',
    emojis: [
      ['❤️', 'red heart love'], ['🧡', 'orange heart'], ['💛', 'yellow heart'], ['💚', 'green heart'], ['💙', 'blue heart'],
      ['💜', 'purple heart'], ['🖤', 'black heart'], ['🤍', 'white heart'], ['🤎', 'brown heart'], ['💔', 'broken heart'],
      ['❣️', 'heart exclamation'], ['💕', 'two hearts'], ['💞', 'revolving hearts'], ['💓', 'beating heart'], ['💗', 'growing heart'],
      ['💖', 'sparkling heart'], ['💘', 'heart arrow cupid'], ['💝', 'heart gift'], ['💟', 'heart decoration'], ['❤️‍🔥', 'heart fire'],
      ['💋', 'kiss mark lips'], ['💯', '100 hundred'], ['💢', 'anger'], ['💥', 'collision boom'], ['💫', 'dizzy stars'],
      ['💦', 'sweat droplets'], ['💨', 'dash wind'], ['🕳️', 'hole'], ['💬', 'speech bubble'], ['💭', 'thought bubble'],
      ['💤', 'zzz sleep'], ['✅', 'check mark done'], ['❌', 'cross x no'], ['❎', 'cross button'], ['➕', 'plus'],
      ['➖', 'minus'], ['➗', 'divide'], ['✖️', 'multiply'], ['❓', 'question'], ['❔', 'white question'],
      ['❗', 'exclamation'], ['❕', 'white exclamation'], ['‼️', 'double exclamation'], ['⁉️', 'exclamation question'], ['💲', 'dollar sign'],
      ['⚠️', 'warning alert'], ['🚸', 'children crossing'], ['⛔', 'no entry'], ['🚫', 'prohibited no'], ['✔️', 'check'],
      ['☑️', 'checkbox'], ['🔘', 'radio button'], ['⭕', 'circle o'], ['🆗', 'ok'], ['🆕', 'new'],
      ['🆒', 'cool'], ['🆓', 'free'], ['🆙', 'up'], ['🈁', 'here'], ['🔝', 'top'],
      ['🔙', 'back'], ['🔛', 'on'], ['🔜', 'soon'], ['🔚', 'end'], ['➡️', 'right arrow'],
      ['⬅️', 'left arrow'], ['⬆️', 'up arrow'], ['⬇️', 'down arrow'], ['↗️', 'up right arrow'], ['↘️', 'down right arrow'],
      ['🔄', 'refresh cycle'], ['🔃', 'clockwise'], ['🔀', 'shuffle'], ['🔁', 'repeat'], ['🔂', 'repeat one'],
      ['▶️', 'play'], ['⏸️', 'pause'], ['⏹️', 'stop'], ['⏺️', 'record'], ['⏭️', 'next track'],
      ['⏮️', 'previous track'], ['⏩', 'fast forward'], ['⏪', 'rewind'], ['🔼', 'up small'], ['🔽', 'down small'],
      ['🔀', 'shuffle'], ['🔉', 'speaker low'], ['🔊', 'speaker loud'], ['🔇', 'muted'], ['📢', 'loudspeaker'],
      ['📣', 'megaphone'], ['🔔', 'bell'], ['🔕', 'no bell mute'], ['🎵', 'music note'], ['🎶', 'music notes'],
      ['➰', 'loop'], ['♻️', 'recycle'], ['⚜️', 'fleur de lis'], ['🔱', 'trident'], ['📛', 'name badge'],
      ['🔰', 'beginner'], ['✳️', 'asterisk'], ['✴️', 'eight star'], ['❇️', 'sparkle'], ['®️', 'registered'],
      ['©️', 'copyright'], ['™️', 'trademark'], ['〽️', 'part alternation'], ['⚕️', 'medical'], ['♾️', 'infinity'],
      ['♀️', 'female sign'], ['♂️', 'male sign'], ['⚧️', 'transgender'], ['☮️', 'peace'], ['☯️', 'yin yang'],
      ['✡️', 'star of david'], ['☪️', 'star crescent'], ['🕉️', 'om'], ['✝️', 'cross'], ['♈', 'aries'],
      ['♉', 'taurus'], ['♊', 'gemini'], ['♋', 'cancer'], ['♌', 'leo'], ['♍', 'virgo'],
      ['♎', 'libra'], ['♏', 'scorpio'], ['♐', 'sagittarius'], ['♑', 'capricorn'], ['♒', 'aquarius'],
      ['♓', 'pisces'], ['⛎', 'ophiuchus'], ['🔟', 'ten'], ['🔢', 'numbers'], ['#️⃣', 'hash'],
    ],
  },
  {
    key: 'flags',
    label: 'Flags',
    icon: '🏁',
    emojis: [
      ['🏁', 'checkered flag finish'], ['🚩', 'triangular flag'], ['🎌', 'crossed flags'], ['🏴', 'black flag'], ['🏳️', 'white flag'],
      ['🏳️‍🌈', 'rainbow pride flag'], ['🏳️‍⚧️', 'transgender flag'], ['🏴‍☠️', 'pirate flag'], ['🇺🇳', 'united nations'], ['🇺🇸', 'usa united states'],
      ['🇬🇧', 'uk united kingdom britain'], ['🇨🇦', 'canada'], ['🇲🇽', 'mexico'], ['🇧🇷', 'brazil'], ['🇦🇷', 'argentina'],
      ['🇨🇴', 'colombia'], ['🇨🇷', 'costa rica'], ['🇬🇹', 'guatemala'], ['🇪🇸', 'spain'], ['🇫🇷', 'france'],
      ['🇩🇪', 'germany'], ['🇮🇹', 'italy'], ['🇵🇹', 'portugal'], ['🇳🇱', 'netherlands'], ['🇷🇺', 'russia'],
      ['🇨🇳', 'china'], ['🇯🇵', 'japan'], ['🇰🇷', 'korea'], ['🇮🇳', 'india'], ['🇦🇺', 'australia'],
    ],
  },
];

export type EmojiEntry = { e: string; k: string };

export const ALL_EMOJIS: EmojiEntry[] = EMOJI_CATEGORIES.flatMap((c) =>
  c.emojis.map(([e, k]) => ({ e, k: `${k} ${c.label}`.toLowerCase() }))
);
